# Generated by Django 3.2.5 on 2022-08-13 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 5, 58, 36, 492378, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 5, 58, 44, 500310, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
