# Generated by Django 3.2.5 on 2022-08-12 19:29

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 19, 29, 8, 381023, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
