# Generated by Django 3.2.5 on 2022-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_trackentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackentry',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
